### ISSUE TITLE
error when saving hazard model run

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/decat_geonode#186]
==> /var/log/uwsgi/decat_geonode.log <==
Internal Server Error: /decat/api/hazard_model_runs/
Traceback (most recent call last):
  File "/home/geosolutions/.venvs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/geosolutions/.venvs/geonode/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 215, in save
    self.instance = self.create(validated_data)
  File "./decat_geonode/views.py", line 259, in create
    run = HazardModelRun.objects.create(**validated_data)
  File "/home/geosolutions/.venvs/geonode/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/geosolutions/.venvs/geonode/lib/python2.7/site-packages/django/db/models/query.py", line 346, in create
    obj = self.model(**kwargs)
  File "./decat_geonode/models.py", line 256, in __init__
    super(HazardModelRun, self).__init__(*args, **kwargs)
  File "/home/geosolutions/.venvs/geonode/lib/python2.7/site-packages/django/db/models/base.py", line 480, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'outputs' is an invalid keyword argument for this function
[pid: 30722|app: 0|req: 365/518] 79.135.50.243 () {50 vars in 1150 bytes} [Wed Sep 20 16:08:36 2017] POST /decat/api/hazard_model_runs/ => generated 54323 bytes in 131 msecs (HTTP/1.1 500) 4 headers in 161 bytes (1 switches on core 0)

**Comment by cezio** [comment]
Fixed in https://github.com/geosolutions-it/decat_geonode/commit/056927261a2eb2d0ae1d9e7e64ead6dab876651a

I've commented this line earlier because of flake8 checks. it was complaining that `outputs` was declared, but not used anywhere.
